image: eicweb.phy.anl.gov:4567/whit/image_recipes/root_base:latest

#docker pull eicweb.phy.anl.gov:4567/whit/image_recipes/ubuntu_base:latest 

stages:
  - build
  - phase2


hcana_docker:
  stage: build  
  tags: 
     - eic0 docker
  script:
     - docker login eicweb.phy.anl.gov:4567 -u whit -p ${CI_IMAGE_BUILD_PAT}
     - cd containers/docker && make build && make publish
       # - docker login eicweb.phy.anl.gov:4567 -u whit -p ${eic0_registry_push_token}
       # - docker tag  whit/image_recipes/ubuntu_base:latest eicweb.phy.anl.gov:4567/whit/image_recipes/ubuntu_base:latest
       # - docker push eicweb.phy.anl.gov:4567/whit/image_recipes/ubuntu_base:latest


hcana_singular:
  tags: 
     - singularity
  stage: phase2
  dependencies:
     - hcana_docker
  script:
     - /bin/bash .gitlabci/setup.sh
     - mkdir -p build
     - cp containers/singularity/Singuilarity Singularity.hcana
     - /bin/bash .gitlabci/build.sh Singularity.hcana && cp singularity.hcana.simg ../build 
     - cp  Singularity.hcana build/.
  artifacts:
      paths:
        - build/Singularity.ubuntu.simg
        - build/Singularity.ubuntu


