image: eicweb.phy.anl.gov:4567/whit/image_recipes/root_base:latest

stages:
  - build
  - build_sing_img
#  - data_tests

hcana_docker:
  stage: build  
  tags: 
     - eic0 docker
  script:
     - docker login eicweb.phy.anl.gov -u whit -p ${CI_IMAGE_BUILD_PAT}
     - cd containers/docker && make release

hcana_singularity:
  tags: 
     - singularity
  stage: build_sing_img
  #when: manual
  dependencies:
     - hcana_docker
  script:
     - cp containers/singularity/Singularity Singularity.hcana
     - cp Singularity.hcana build/.
#- /bin/bash .gitlabci/setup.sh
#- mkdir -p build
#- pwd
#- /bin/bash .gitlabci/build.sh Singularity.hcana
#- cp Singularity.hcana.simg build/.
  artifacts:
      paths:
        - build/Singularity.hcana
#- build/Singularity.hcana.simg

elastic_tests:
  #stage: data_tests
  dependency: hcana_singularity
  script:
     - bash tests/elastic_test.sh
